# Generated by Django 4.2.1 on 2023-11-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(null=True)),
                ("duration", models.IntegerField()),
                ("created_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
